services:
  postgres:
    image: postgres
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - campaigns:/data/campaigns
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  campaigns: